#!/bin/bash
gulp prod
DATE=`date +%Y-%m-%d:%H:%M:%S`
cd build
git add -u
git add .
git commit -m "build $DATE"
git push prod master || { echo 'push failed' ; exit 1; }
cd ..
echo "build $DATE sent & deployed !"